### ISSUE TITLE
progetto QGIS con tre relazioni

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_plugin_selectbyrelationship#1]
Ho realizzato un progetto QGIS con `TRE relazioni` e trovo un comportamento strano rispetto al progetto con `DUE relazioni`: in quest'ultimo le selezioni sono corrette e a cascata, in quello a TRE, NON considera la terza relazione partendo dalla selezione del layer figlio 'tabella_arm'

dati e progetto sono presenti in code

video demo : https://youtu.be/t4KHTlNZHEs

@slarosa
@aborruso

**Comment by slarosa** [comment]
Questa non me la riesco a spiegare. Investigherò!

**Comment by slarosa** [comment]
@pigreco il progetto con due relazioni sembra avere qualche problema: ne vedo solo una e all'avvio mi chiede di impostare il percorso del db in quanto punta alla tua cartella locale. Puoi sistemare?

**Comment by pigreco** [comment]
@slarosa  il progetto è già impostato con percorsi relativi, strano che punti alla mia cartella locale.

[progetto_due_relazioni.zip](https://github.com/pigreco/test_plugin_selectbyrelationship/files/962886/progetto_due_relazioni.zip)

**Comment by slarosa** [comment]
@pigreco fixed!

**Comment by pigreco** [comment]
@slarosa appena testato, MERAVIGLIOSO!!!
