### ISSUE TITLE
minidump chiusura su plugin attivo

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_plugin_selectbyrelationship#2]
Noto che se chiudo QGIS con plugin attivo (icona attiva) e tabelle attributi aperta con selezione attiva, QGIS presenta un minidump.

@slarosa
@aborruso

**Comment by slarosa** [comment]
@pigreco Succede sempre oppure è occasionale?

**Comment by pigreco** [comment]
@slarosa succede sempre!!!

**Comment by slarosa** [comment]
@pigreco sistemato (vedi https://github.com/slarosa/selectbyrelationship_repo/commit/e737dba5e2d725c42801c841ddd20be775c95d91)

**Comment by pigreco** [comment]
@slarosa buongiorno,
per non scaricare ogni volta l'intero plugin, ho solo copiato ed incollato il fix relativo al minidump (non so se è la procedura corretta) riavviato qgis; NOTO che compare errore python appena attivo il plugin.

è corretto fare il copia incolla del solo file?

**Comment by pigreco** [comment]
@slarosa risolto,
funziona bene!!! 👍
