### ISSUE TITLE
self.sFr.selectChildFromParent = True - non funziona bene

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_plugin_selectbyrelationship#4]
usando il [progetto ](https://github.com/pigreco/test_plugin_selectbyrelationship/blob/master/progetto_una%20relazione_196_E_197_TRUE.qgs) e le seguenti impostazione del plugin:
![n5](https://cloud.githubusercontent.com/assets/7631137/25488972/c7af51d8-2b68-11e7-9eb3-7a8832c3bf9e.jpg)
si presenta sempre errore python sulla deselezione e non funziona il filtro;
test da fare:
1. aprire progetto;
2. attivare plugin;
3. selezionare layer padre (pti_pill);
4. tasto funzione F3 e ricercare nel campo 'rif_quadro' Q10;
5. NOTO: 
5.1 ne trova solo 1, invece sono tanti, anche se il messaggio è corretto;
5.2 se provo a deselezionare, errore python

@slarosa
@aborruso

**Comment by slarosa** [comment]
@pigreco sistemato! thanks!

**Comment by slarosa** [comment]
come da https://github.com/slarosa/selectbyrelationship_repo/commit/8b6ebab2baac5eaefc8b51d6bb88ae30ead95e93

**Comment by pigreco** [comment]
@slarosa ho riscaricato il plugin, ma ottengo sempre gli stessi errori.

**Comment by slarosa** [comment]
con il progetto ed i passaggi che hai descritto a me seleziona 13 features 'Q10' e 13 righe su tabella_arm. Prova a controllare che il codice che hai scaricato contiene il fix slarosa/selectbyrelationship_repo@8b6ebab

**Comment by pigreco** [comment]
@slarosa perfetto, prova fatta con successo!!! 👍
