### ISSUE TITLE
stato attivo/disattivo

### ISSUE THREAD

**Issue by pigreco** [pigreco/test_plugin_selectbyrelationship#6]
@slarosa noto che una volta attivato il plugin resta attivo anche dopo 'spegnimento' del bottone.

**Comment by slarosa** [comment]
@pigreco stai usando la versione della repository di QGIS o quella scaricata dalla mia repository?
Io ho provato entrambe ma non noto il problema.

In ogni caso, se per te non è un problema, visto che adesso il plugin è nella repository ufficiale di QGIS conviene fare le segnalazioni sulla repo di Luca, per consentire a chi ha lo stesso problema di seguire lo stesso thread, ma anche per evitare un'eccessiva dispersione delle segnalazioni. 

Potremmo comunque pensare di linkare la tua repo per i progetti di esempio, che ne dici?

**Comment by pigreco** [comment]
@slarosa ho appena scaricato la versione dal repository ufficiale e tutto è OK;
ma ritrovo il problema del minidump su chiusura QGIS e plugin attivo.

apro issues nella repo di Luca.
per me va bene linkare la mia repo.
